# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Davatronic
permalink: pretty
slider-titre: Cryptage Informatique et Protection de données
slider-sous-titre: 
coming-soon-background-image: "/uploads/6211631cc5efb244d31e204f6ffc91d7_accueil-studio_1500-999.jpeg"
footer-text: texte de bas de page
phone: 44449553935
email: test@email.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  programmes:
    output: true
    permalink: /:collection/:title
  slides:
    output: true
    permalink: /:collection/:title
  temoignages:
    output: true
    permalink: /:collection/:title


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock